### ISSUE TITLE
Very long load times

### ISSUE THREAD

**Issue by poacher2k** [haekb/nolf1-modernizer#10]
Hi!

First off, thank you for your work on this. It's looking really promising.

I'm experiencing very long load times with this (eg. 13s), whereas without it, loading is almost instant. 

Not sure what's causing this, but I hope you might :)

**Comment by haekb** [comment]
Thanks for the report, this should be fixed in the upcoming patch. In the mean time, disable animated load screens (like I mentioned on the discord.) That should clear it up!

**Comment by haekb** [comment]
This has been fixed in the next update!
