### ISSUE TITLE
Missing "Begin next mission" arrow on Mission Summary

### ISSUE THREAD

**Issue by poacher2k** [haekb/nolf1-modernizer#11]
With modernizer:
![image](https://user-images.githubusercontent.com/2255960/65868557-cb6cda00-e378-11e9-82c3-c18dc2940f86.png)

Without:
![image](https://user-images.githubusercontent.com/2255960/65868653-f9521e80-e378-11e9-8dd6-6b5564466cc4.png)

**Comment by haekb** [comment]
This has been fixed in the next update!
