### ISSUE TITLE
Setting the FOV

### ISSUE THREAD

**Issue by Keith94** [haekb/nolf1-modernizer#26]
The game has CVARs `+fovx ""` and `+fovy ""` but when trying different values it seems to produce a distorted image.

Is there some kind of method or formula needed to set a custom FOV correctly?

**Comment by haekb** [comment]
I somehow don't get notified about issues 🤔 

Sorry for the delay, I'm not sure. I do know they both need to be specified in NOLF 2, but I haven't looked into it for 1. I suggest maybe trying settings your preferred horizontal fov (fovx) and then looking online at a horizontal to vertical calculator, that should give you the proper fovy value.
