### ISSUE TITLE
Missing music from jukebox

### ISSUE THREAD

**Issue by mzso** [haekb/nolf1-modernizer#32]
I think the "main theme" is missing one item, intensity 3 in the text file (amb1.sgt, amb2.sgt, etc).

Also, It looks like in the GOTY music section the "Investigate" music transitions into Ambiance after one iteration and stays on that thereafter.

**Comment by SPAWN-nolf** [comment]
The missing IDS text are strings for "Now Playing:" and "themes"

**Comment by haekb** [comment]
Hey there, 

On my quest to localize hard coded strings, I've re-worked how the jukebox finds its songs. I'll be looking into intensity 3 for the next patch.

Regarding the GOTY music section, it's just kinda how the DirectMusic system works. I don't think I'll be modifying that as it would require quite a bit of testing!

**Comment by mzso** [comment]
[**@haekb**](https://github.com/haekb) commented on [2020. máj. 6. 00:39 CEST](https://github.com/haekb/nolf1-modernizer/issues/32#issuecomment-624343561 "2020-05-05T22:39:05Z - Replied by Github Reply Comments"):
> Regarding the GOTY music section, it's just kinda how the DirectMusic system works. I don't think I'll be modifying that as it would require quite a bit of testing!

It doesn't transition from one intensity to another with any of the other music.
It's weird. None of the the other music has any instance specified in the text file that goes from one music to another. Only this. Switching only happens purposefully with all others. For example going from ambient to an action music when starting to combat with enemies.
