### ISSUE TITLE
Use release in GitHub

### ISSUE THREAD

**Issue by Saibamen** [haekb/nolf1-modernizer#39]
Hello,

Please use release feature in GitHub, when new version is deployed: https://github.com/haekb/nolf1-modernizer/releases

**Why?**
People can "subscribe" to release watch for specific repos in GH: 
![obraz](https://user-images.githubusercontent.com/905878/83053834-e8a99380-a040-11ea-8622-7cfde7ef3c4b.png)

**Comment by haekb** [comment]
This repo is for development use. Releases will be packaged up and posted here: https://haekb.itch.io/nolf-modernizer

**Comment by Saibamen** [comment]
ehh, no. Let me ask question: How can I submit to any newsletter when new version released in https://haekb.itch.io/nolf-modernizer?

In GitHub - you have this functionality already
