### ISSUE TITLE
Fullscreen mode

### ISSUE THREAD

**Issue by Saibamen** [haekb/nolf1-modernizer#40]
Hello,

I want to set my native resolution (1920 x 1080 x 32) on the full screen.
Settings:
![obraz](https://user-images.githubusercontent.com/905878/83054658-4b4f5f00-a042-11ea-9b0d-705a705f98dd.png)

**Actual**
No fullscreen, just window which is also present on my second monitor

Screen (Firefox is in full screen at second monitor, see also missing Windows button):
![obraz](https://user-images.githubusercontent.com/905878/83055199-0bd54280-a043-11ea-9132-752637d205be.png)

**Expected**
Able to set fullscreen mode, game is only visible on one monitor.

**Comment by haekb** [comment]
I've seen this problem before, but I can't remember the exact solution. Make sure you've installed all the files (including the custom d3d.ren!), and try changing the windows scale to 100% if you haven't already.
![image](https://user-images.githubusercontent.com/3683240/84174739-d4e43100-aa33-11ea-9340-f8c3feaa30e0.png)

NOLF 1 is particularly finicky about that.

If you have any issues running the game with the custom d3d.ren then install the latest visual c++ redistribute. 
https://aka.ms/vs/16/release/vc_redist.x86.exe

**Comment by Saibamen** [comment]
Ok, main bug was "fixed" by this workaround, but now I see wrong positioned text:
![lithtech-2020-06-11-13-40-02-79](https://user-images.githubusercontent.com/905878/84381878-3560a300-abd9-11ea-99f9-4e51a2048dc0.png)
![lithtech-2020-06-11-13-39-37-10](https://user-images.githubusercontent.com/905878/84381882-3691d000-abd9-11ea-9bbf-8c87a2384daa.png)

**Comment by haekb** [comment]
You don't have the mod enabled correctly. The UI will be fullscreened when it's enabled.

Please follow the readme instructions.

**Comment by Saibamen** [comment]
Hmm. Today I started game again, I didn't change anything from previous setup and now main menu looks OK. Maybe it is some regression?
